name: Tests and Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['13.x', '12.x', '10.x']
    name: Node v${{ matrix.node-version }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start mongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Run server tests
        run: |
          cd server
          npm install
          npm run test:run

      - name: Run client tests & build
        run: |
          cd client
          npm install
          npm test
          npm run build
        env:
          CI: true
          NODE_PATH: src/
