name: Run Tests and Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '10', '8']
    name: Node v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run server tests
        run: |
          npm install
          npm test
      - name: Run client tests & build
        run: |
          npm run client:install
          npm run client:test
          npm run client:build
